from lib.html.html import HtmlElement

FOOTER_CLASS_HTML_ATTRIBUTES = "doc-footer"
FOOTER_CONTAINER_CLASS_HTML_ATTRIBUTES = "container text-center"
FOOTER_SPAN_CLASS_HTML_ATTRIBUTES = "text-muted"
FOOTER_TEXT = "Generated by RemoveTanks! Docs Generator."


class FooterHtmlGenerator(object):
    def generate_html(self):
        try:
            return HtmlElement("footer", attributes={
                "class": FOOTER_CLASS_HTML_ATTRIBUTES
            }, children=[
                HtmlElement("div", attributes={
                    "class": FOOTER_CONTAINER_CLASS_HTML_ATTRIBUTES
                }, children=[
                    HtmlElement("span", attributes={
                        "class": FOOTER_SPAN_CLASS_HTML_ATTRIBUTES
                    }, text=FOOTER_TEXT)
                ])
            ])
        except Exception as e:
            raise FooterHtmlGenerationException(e)


class FooterHtmlGenerationException(Exception):
    MESSAGE_TEMPLATE = "Cannot generate footer html. Cause: {}."

    def __init__(self, cause):
        super().__init__(self.MESSAGE_TEMPLATE.format(cause))
