from lib.html.html import HtmlElement


class FooterHtmlGenerator(object):
    def generate_html(self):
        try:
            html = HtmlElement("div")
            html.add_child(HtmlElement("p", "Generated by Remove Tanks! docs generator tool."))

            return html
        except Exception as e:
            raise FooterHtmlGenerationException(e)


class FooterHtmlGenerationException(Exception):
    MESSAGE_TEMPLATE = "Cannot generate footer html. Cause: {}."

    def __init__(self, cause):
        super().__init__(self.MESSAGE_TEMPLATE.format(cause))
